import fetch from 'node-fetch';
import fs from 'fs';
import FormData from 'form-data';

const BASE_URL = 'http://localhost:3000/api';
let results = [];

function assert(condition, message) {
    if(!condition) {
        results.push({ test: message, result: 'FAIL' });
        return false;
    }
    results.push({ test: message, result: 'PASS' });
    return true;
}

async function run() {
    console.log("Starting API Audit...");

    // 1. Session Info & Role Validation
    let loginRes = await fetch(`${BASE_URL}/auth/login`, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: "admin@bhoomisetu.gov.in", password: "admin123" })
    }).then(r => r.json());
    let adminToken = loginRes.token;
    assert(loginRes.user.role === 'Super Admin', "Super Admin login returns correct role");

    let laoLoginRes = await fetch(`${BASE_URL}/auth/login`, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: "lao.district@bhoomisetu.gov.in", password: "password123" })
    }).then(r => r.json());
    let laoToken = laoLoginRes.token;
    assert(laoLoginRes.user.role === 'District LAO', "LAO login returns correct role");

    // 2. Proposal Creation & Backend Validation
    let invalidPropRes = await fetch(`${BASE_URL}/proposals`, {
        method: "POST", headers: { "Content-Type": "application/json", "Authorization": `Bearer ${adminToken}` },
        body: JSON.stringify({ projectName: "", ministry: "InvalidMinistry", category: "HighWay", state: "Haryana", district: "Mumbai", areaRequired: -5, action: "submit" })
    });
    assert(invalidPropRes.status === 400, "Backend rejects invalid enum/empty payload");

    // Rejection without reason
    // Let's create a valid proposal first
    let validPropRes = await fetch(`${BASE_URL}/proposals`, {
        method: "POST", headers: { "Content-Type": "application/json", "Authorization": `Bearer ${adminToken}` },
        body: JSON.stringify({ projectName: "Test expressway", ministry: "MoUD", category: "Urban Development", state: "Haryana", district: "Gurugram", areaRequired: 10, action: "submit", footprint: JSON.stringify({type: "Polygon", coordinates: [[[0,0],[0,1],[1,1],[0,0]]]}) })
    });
    let validProp = await validPropRes.json();
    assert(validProp.success, "Backend accepts valid proposal creation");
    let propId = validProp.proposal.id;

    // LAO tries to edit Admin's proposal (which is Haryana, Gurugram... but wait, LAO is Delhi/South Delhi)
    let laoEditRes = await fetch(`${BASE_URL}/proposals/${propId}`, {
        method: "PATCH", headers: { "Content-Type": "application/json", "Authorization": `Bearer ${laoToken}` },
        body: JSON.stringify({ projectName: "Hacked" })
    });
    // Wait, the endpoints might not have PATCH. Let's check rejection.
    let rejectRes = await fetch(`${BASE_URL}/proposals/${propId}/workflow`, {
        method: "POST", headers: { "Content-Type": "application/json", "Authorization": `Bearer ${adminToken}` },
        body: JSON.stringify({ actionId: "REJECT", remarks: "" })
    });
    assert(rejectRes.status === 400, "Backend rejects REJECT without reason");

    let validRejectRes = await fetch(`${BASE_URL}/proposals/${propId}/workflow`, {
        method: "POST", headers: { "Content-Type": "application/json", "Authorization": `Bearer ${adminToken}` },
        body: JSON.stringify({ actionId: "REJECT", remarks: "Invalid docs" })
    });
    let validReject = await validRejectRes.json();
    assert(validReject.success && validReject.proposal.status === 'REJECTED', "Backend accepts REJECT with reason");

    // Document upload checksum
    fs.writeFileSync('audit_doc.pdf', 'dummy content');
    const form = new FormData();
    form.append('file', fs.createReadStream('audit_doc.pdf'));
    let docRes = await fetch(`${BASE_URL}/proposals/${propId}/documents`, {
        method: "POST", headers: { "Authorization": `Bearer ${adminToken}`, ...form.getHeaders() },
        body: form
    });
    let docData = await docRes.json();
    assert(docRes.status === 200 && docData.document && docData.document.checksum, "Document uploaded with checksum generated by backend");
    
    console.log(JSON.stringify(results, null, 2));
}

run();
